spring:
  datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/sas?serverTimezone=UTC&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&socketTimeout=30000
      username: sas
      password: sas1!

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    open-in-view: false

logging:
  level:
    root: info
    org.springframework.web: debug

server:
  port: 20010
